debug: "true"

log:
  level: "debug"

app:
  name: "darkroom"
  version: "1.0.0"
  description: "A realtime image processing service"

source:
  kind: "S3"
  hystrix:
    commandName: "S3_STORAGE"
    timeout: 5000
    maxConcurrentRequests: 100
    requestVolumeThreshold: 10
    sleepWindow: 10
    errorPercentThreshold: 25
  bucket:
    name: "myAwesomeBucket"
    region: "region"
    accessKey: "randomAccessKey"
    secretKey: "superSecret"
  pathPrefix: "/prefixPath/to/folder"

port: 3000

cache:
  time: 31536000    # One year

enableConcurrentImageProcessing: true

newrelic:
  enabled: false
  appName: "darkroom"
  license: "eu01xxf0b661e019e030a14ca63e50bf12345678"
